import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/components/header'
import slider from 'images/slider.png'
import { Bounce } from 'react-reveal'
import { Button } from 'flowbite-react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dateSeconds = new Date(2023, 1, 25)
  console.log(dateSeconds)
  setInterval(function() {
    const countDownDate = dateSeconds.getTime();
    const now = new Date().getTime();
    const distance = countDownDate - now;
    const days = Math.floor(distance / (1000 * 60 * 60 * 24));
    const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    const seconds = Math.floor((distance % (1000 * 60)) / 1000);
    const arr = (val) => Array.from(String(val), String)

    document.getElementById("countDays").innerHTML = String(arr(days).length > 1 ? days : `0${days}`)
    document.getElementById("countHours").innerHTML = String(arr(hours).length > 1 ? hours : `0${hours}`)
    document.getElementById("countMins").innerHTML = String(arr(minutes).length > 1 ? minutes : `0${minutes}`)
    document.getElementById("countSecs").innerHTML = String(arr(seconds).length > 1 ? seconds : `0${seconds}`)
  }, 1000);
  return (
    <>
      <Head>
        <title>Election Update</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/logo.png" />

        {/* bootstrap cdn  */}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />

      </Head>
      <div className='w-full'>
        <Header />
        <div className='w-full'>
          <div className='w-full'>
            <Image alt='vote' src={slider} className="w-full h-screen" />
          </div>

          <div className='w-full p-10 container-sm'>
            <div className='row'>
              <div className='col-md-6'>
                <Bounce left>
                  <div className='sm:border border-green rounded-xl py-4'>
                    <div className='px-4'>
                      <p className='font-medium'>Countdown to </p>
                      <p className='text-xl font-bold'>2023 Election </p>
                    </div>
                    <div className='bg-dim_green p-1 text-white ml-4'>
                      <p className='font-bold m-0 p-0'>Presidential and National Assemblies</p>
                      <p className='italic m-0 p-0'>25th February, 2023</p>
                    </div>
                    <div className='px-4 pt-2 flex justify-between gap-2'>
                      <div className='bg-light w-100 text-center pb-2'>
                        <p className='font-bold text-xl'>Days</p>
                        <p className='text-5xl font-bold' id='countDays'>00</p>
                      </div>
                      <div className='bg-light w-100 text-center pb-2'>
                        <p className='font-bold text-xl'>Hours</p>
                        <p className='text-5xl font-bold' id='countHours'>00</p>
                      </div>
                      <div className='bg-light w-100 text-center pb-2'>
                        <p className='font-bold text-xl'>Mins</p>
                        <p className='text-5xl font-bold' id='countMins'>00</p>
                      </div>
                      <div className='bg-light w-100 text-center pb-2'>
                        <p className='font-bold text-xl'>Secs</p>
                        <p className='text-5xl font-bold' id='countSecs'>00</p>
                      </div>
                    </div>
                    <div className='px-4 pt-4 flex justify-between'>
                      <div className='w-[20%] h-[15px] rounded-full bg-light'>
                        <div className='w-[50%] rounded-full h-[80%] bg-green' />
                      </div>
                      <Button size="xs" className="md:px-10 font-bold border-0 hover:opacity-60 text-center rounded-full bg-gradient-to-br from-red to-dark_red text-white">
                        Read More
                      </Button>
                    </div>
                  </div>
                </Bounce>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
